.TH WVDIAL 1 "December 2005" "WvDial"
.\"
.SH NAME
wvdial \- PPP dialer with built-in intelligence.
.\"
.SH SYNOPSIS
.B wvdial
[
.I OPTIONS
]
[
.I SECTION
] ...
.\"
.SH DESCRIPTION
.B wvdial
is an intelligent PPP dialer, which means that it dials a modem and
starts PPP in order to connect to the Internet.  It is something like the
.BR chat (8)
program, except that it uses heuristics to guess how to dial and log
into your server rather than forcing you to write a login script.
.PP
When
.B wvdial
starts, it first loads its configuration from
.IR /etc/wvdial.conf
and
.IR ~/.wvdialrc
which contains basic information about the modem port, speed, and init
string, along with information about your Internet Service Provider (ISP),
such as the phone number, your username, and your password.
.PP
Then it initializes your modem and dials the server and waits for a 
connection (a CONNECT string from the modem).  It understands and responds 
to typical connection problems (like BUSY and NO DIALTONE).
.PP
Any time after connecting, 
.B wvdial
will start PPP if it sees a PPP sequence from the server.  Otherwise,
it tries to convince the server to start PPP by doing the following:
.IP \(bu 4
responding to any login/password prompts it sees;
.IP \(bu
interpreting \(lqchoose one of the following\(rq-style menus;
.IP \(bu
eventually, sending the word \(lqppp\(rq (a common terminal server command).
.PP
If all of this fails,
.B wvdial
just runs
.BR pppd (8)
and hopes for the best. It will bring up the connection, and then wait
patiently for you to drop the link by pressing CTRL\-C.
.\"
.SH OPTIONS
Several options are recognized by
.BR wvdial .
.TP
.B \-c, \-\-chat
Run wvdial as a chat replacement from within pppd, instead of the more
normal method of having wvdial negotiate the connection and then call
pppd.
.TP
.B \-C, \-\-config=CONFIGFILE
Run wvdial with CONFIGFILE as the configuration file, instead of
.IR /etc/wvdial.conf .
This is mainly useful only if you want to have per-user
configurations, or you want to avoid having dial-up information (usernames,
passwords, calling card numbers, etc.) in a system wide configuration file.
.TP
.B \-n, \-\-no\-syslog
Don't output debug information to the syslog daemon (only useful together
with \-\-chat).
.PP
.B wvdial
is normally run without command line options, in which case it reads
its configuration from the
.I "[Dialer Defaults]"
section of
.IR /etc/wvdial.conf .
(The configuration file is described in more detail in
.BR wvdial.conf (5)
manual page.)
.PP
One or more 
.IR SECTION s
of
.I
/etc/wvdial.conf
may be specified on the command line.  Settings in these sections will
override settings in
.IR "[Dialer Defaults]" .
.PP
For example, the command:
.RS
.B wvdial phone2
.RE
will read default options from the
.I "[Dialer Defaults]"
section, then override any or all of the options with those found in the
.I "[Dialer phone2]"
section.
.PP
If more than one section is specified, they are processed in the order they
are given.  Each section will override all the sections that came before it.
.PP
For example, the command:
.RS
.B wvdial phone2 pulse shh
.RE
will read default options from the
.I "[Dialer Defaults]"
section, then override any or all of the options with those found in the
.I "[Dialer phone2]"
section, followed by the
.I "[Dialer pulse]"
section, and lastly the
.I "[Dialer shh]"
section.
.PP
Using this method, it is possible to easily configure
.B wvdial
to switch between different internet providers, modem init strings,
account names, and so on without specifying the same configuration
information over and over.
.\"
.SH BUGS
\(lqIntelligent\(rq programs are frustrating when they don't work right.
This version of
.B wvdial
has only minimal support for disabling or overriding its \(lqintelligence\(rq,
with the \(lqStupid Mode\(rq, \(lqLogin Prompt\(rq, and \(lqPassword 
Prompt\(rq options.
So, in general if you have a nice ISP, it will probably work,
and if you have a weird ISP, it might not.
.PP
Still, it's not much good if it doesn't work for you, right?  Don't be fooled
by the fact that
.B wvdial
finally made it to version 1.00; it could well contain many bugs and 
misfeatures.  Let us know if you have problems by sending e-mail to
.BR <wvdial\-list@lists.nit.ca> .
.PP
You may encounter some error messages if you don't have write access to
.B /etc/ppp/pap\-secrets
and
.BR /etc/ppp/chap\-secrets .
Unfortunately, there's really no nice way around this yet.
.SH FILES
.TP
/etc/wvdial.conf
Configuration file which contains modem, dialing, and login
information. See 
.BR wvdial.conf (5).
.TP
/dev/ttyS*
Serial port devices.
.TP
/etc/ppp/peers/wvdial
Required for correct authentication in pppd version 2.3.0 or newer.
.TP
/etc/ppp/{pap,chap}\-secrets
Contains a list of usernames and passwords used by pppd for authentication.
.B wvdial
maintains this list automatically.
.\"
.SH AUTHORS
Dave Coombs and Avery Pennarun for Net Integration Technologies.
We would also like to thank SuSE and
RedHat for adding a number of various cool features to
.BR wvdial .
Thanks guys!
.\"
.SH SEE ALSO
.BR wvdial.conf (5),
.BR wvdialconf (1),
.BR pppd (8),
.BR chat (8).

